name: Deploy-ADF-Production

on:
  push:
    branches:
      - main # Se activa al hacer push o merge a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Bajamos el código de la rama adf_publish (donde están las plantillas)
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish

      # 2. Login en Azure usando tu secreto
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Despliegue de la plantilla ARM
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: "rg-Oscar-DEV" # Asegúrate de tener este secreto
          # Ajusta la ruta si tu carpeta tiene un nombre específico
          template: ./adfsprojectosc97dev/ARMTemplateForFactory.json 
          parameters: >
            ./adfsprojectosc97dev/ARMTemplateParametersForFactory.json
            factoryName="adfsprojectosc97prod"
            # URL DEL KEY VAULT (Punto de acceso a secretos)
            # akvdev_properties_typeProperties_baseUrl="https://kvprojectosc13.vault.azure.net/"
            
            # ID DEL CLUSTER (Conexión física)
            ls_adb_prod_properties_typeProperties_existingClusterId="0414-175402-ycrjrf77"
            
            # RUTA DEL NOTEBOOK (Solo si lograste parametrizar el 'path' como vimos antes)
            PP_PROECT_OSCAR_DEV_properties_parameters_path_defaultValue="/Workspace/Users/duque.smart1397@outlook.com/deploy/"
