name: Deploy-ADF-Production

on:
  push:
    branches:
      - main # Se activa al hacer push o merge a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Bajamos el código de la rama adf_publish (donde están las plantillas)
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish

      # 2. Login en Azure usando tu secreto
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Despliegue de la plantilla ARM
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: "rg-Oscar-DEV" # Asegúrate de tener este secreto
          # Ajusta la ruta si tu carpeta tiene un nombre específico
          template: ./adfsprojectosc97dev/ARMTemplateForFactory.json 
          parameters: >
            ./adfsprojectosc97dev/ARMTemplateParametersForFactory.json
            factoryName="PP_PROJECT_DATA_FACTORY_PROD"
            PP_PROECT_OSCAR_DEV_properties_parameters_linked_service_defaultValue="ls_adb_prod"
            PP_PROECT_OSCAR_DEV_properties_parameters_base_path_defaultValue="/Workspace/Users/duque.smart1397@outlook.com/deploy/"
